version: '3.8'

services:
  mysql:
    image: mysql:5.7
    container_name: mysql-hotel
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: hotel
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - hotel-network

  backend:
    build:
      context: ./backend
    container_name: backend-hotel
    depends_on:
      - mysql
    environment:
      DB_HOST: mysql
      DB_USER: root
      DB_PASSWORD: root
      DB_NAME: hotel
      DB_PORT: 3306
    ports:
      - "5000:5000"
    networks:
      - hotel-network

volumes:
  db_data:

networks:
  hotel-network:
